service: ${self:custom.appName}-dynamodb
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  profile: default
  environment:
    STAGE: ${self:provider.stage}
    PREFIX: ${self:custom.appName}-${self:provider.stage}
    VTUBER_ID_SEQUENCE: ${self:provider.environment.PREFIX}-vtuber-sequence
    VTUBER_INFO_TABLE: ${self:provider.environment.PREFIX}-vtuber-info
    MEMBER_TYPE_MASTER_TABLE: ${self:provider.environment.PREFIX}-member-type-master
plugins:
  - serverless-dynamodb-local
custom:
  defaultStage: dev
  appName: vtuber-server
  dynamodb:
    stages: dev
    start:
      port: 8082
      inMemory: true
      migrate: true
      seed: true
    seed:
      vtuberIdSequence:
        sources:
          - table: ${self:provider.environment.VTUBER_ID_SEQUENCE}
            sources: [./src/db/seeds/vtuber-id-sequence.json]
      vtuberInfo:
        sources:
          - table: ${self:provider.environment.VTUBER_INFO_TABLE}
            sources: [./src/db/seeds/vtuber-info.json]
      memberTypeMaster:
        sources:
          - table: ${self:provider.environment.MEMBER_TYPE_MASTER_TABLE}
            sources: [./src/db/seeds/member-type-master.json]
resources:
  Resources:
    VtuberIdSequence:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VTUBER_ID_SEQUENCE}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    VtuberInfo:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.VTUBER_INFO_TABLE}
        AttributeDefinitions:
          - AttributeName: vtuberId
            AttributeType: S
        KeySchema:
          - AttributeName: vtuberId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    MemberTypeMaster:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MEMBER_TYPE_MASTER_TABLE}
        AttributeDefinitions:
          - AttributeName: memberTypeCd
            AttributeType: S
        KeySchema:
          - AttributeName: memberTypeCd
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
